<a href="https://colab.research.google.com/github/mrdbourke/pytorch-deep-learning/blob/v0/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TK - intro to PyTorch

## TK - What is PyTorch?

## TK - What can PyTorch be used for?

## TK - Who uses PyTorch?

## TK - Why use PyTorch?

Researchers love using PyTorch -- https://paperswithcode.com/trends 

## TK - What we're going to cover in this module...

* Introduction to Tensors
* Creating tensors
* Getting information from tensors
* Manipulating tensors
* Tensor operations (neural networks involve manipulating tensors...)
* Tensors and NumPy
* Running tensors on GPU





In [2]:
import torch
print(torch.__version__)

1.9.0+cu111


## TK - Introduction to tensors 


### TK - Creating tensors 

All you need to know - https://pytorch.org/docs/stable/generated/torch.tensor.html#torch.tensor

Many different ops for PyTorch tensors - https://pytorch.org/docs/stable/torch.html

In [8]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim

0

In [97]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
# Matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
matrix.ndim

2

In [16]:
# Tensor
tensor = torch.tensor([[[3, 6, 9],
                        [3, 6, 9],
                        [3, 6, 9]]])
tensor

tensor([[[3, 6, 9],
         [3, 6, 9],
         [3, 6, 9]]])

In [17]:
tensor.ndim

3

In [19]:
# Note: torch.tensor() always makes a copy
tensor_A = torch.tensor([1, 2, 3])
tensor_B = torch.tensor(tensor_A) # Creating a tensor like this produces a warning

tensor_A, tensor_B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [20]:
# Change tensor_B, doesn't change tensor_A
tensor_B[0] = 4

tensor_A, tensor_B

(tensor([1, 2, 3]), tensor([4, 2, 3]))

In [21]:
# Change tensor_A, doesn't change tensor_B
tensor_A[1] = 4

tensor_A, tensor_B

(tensor([1, 4, 3]), tensor([4, 2, 3]))

In [27]:
# Random
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6109, 0.1709, 0.9683, 0.5726],
         [0.6924, 0.6208, 0.8857, 0.1900],
         [0.7239, 0.4225, 0.0904, 0.8145]]), torch.float32)

In [29]:
# Zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [30]:
# torch.arange(), torch.range() is deprecated 
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [24]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

float_16_tensor.dtype

torch.float16

## TK - Getting information from tensors

In [34]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7211, 0.2743, 0.2621, 0.0821],
        [0.0890, 0.7967, 0.8323, 0.2623],
        [0.8343, 0.2572, 0.4677, 0.1218]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## TK - Manipulating tensors (tensor operations)

### Basic operations

In [94]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [44]:
tensor * 10

tensor([10, 20, 30])

In [45]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [46]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [47]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [48]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [49]:
# Original tensor is still unchanged 
tensor

tensor([1, 2, 3])

In [55]:
# Element-wise multiplication
tensor * tensor

tensor([1, 4, 9])

### Matrix multiplcation

Neural networks are mostly matrix multiplcation - https://marksaroufim.substack.com/p/working-class-deep-learner



In [50]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [51]:
torch.matmul(tensor, tensor)

tensor(14)

In [54]:
tensor @ tensor

tensor(14)

In [58]:
sum(tensor * tensor.T)

tensor(14)

In [60]:
# By hand (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

tensor(14)

In [66]:
# Shapes need to be in the right way (this will error) 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 8],
                         [9, 10], 
                         [11, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

In [67]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 23.,  29.,  35.],
        [ 53.,  67.,  81.],
        [ 83., 105., 127.]])

In [79]:
# This uses matrix mutliplcation...
linear = torch.nn.Linear(in_features=3, out_features=2)
input = tensor_A
output = linear(input.T)
output, output.shape

(tensor([[ 1.4391, -1.4383],
         [ 1.5400, -1.5229]], grad_fn=<AddmmBackward>), torch.Size([2, 2]))

In [80]:
tensor_A.T.shape

torch.Size([2, 3])

### TK - Finding the min, max, mean, sum, etc (aggregation)

See here for more operations - https://pytorch.org/docs/stable/tensors.html



In [103]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [104]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [106]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### TK - Positional min/max

In [83]:
# Returns index of max value
tensor = torch.arange(10, 100, 10)
tensor, tensor.argmax()

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(8))

In [86]:
# Returns index of min value
tensor = torch.arange(10, 100, 10)
tensor, tensor.argmin()

(tensor([10, 20, 30, 40, 50, 60, 70, 80, 90]), tensor(0))

### TK - Change tensor datatype

See torch datatypes here - https://pytorch.org/docs/stable/tensors.html 

In [87]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [92]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [93]:
tensor_int32 = tensor.type(torch.int32)
tensor_int32

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int32)

### TK - Reshaping, stacking, squeezing and unsqueezing

Why do any of these?

Avoid for loops in your tensor code.

For loops slow things down.

In [107]:
x = torch.arange(1., 8.)
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [115]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [123]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [116]:
# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [120]:
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

## TK - PyTorch tensors & NumPy

In [130]:
# NumPy array to tensor
import numpy as np
array = np.arange(1, 8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [131]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [134]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [135]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## TK - Reproducibility

* Create tensors with same values...
* Show PyTorch random seed so we can all use similar values

See: https://pytorch.org/docs/stable/notes/randomness.html

## TK - Running tensors on GPUs 

In [137]:
# Check for GPU
import torch
torch.cuda.is_available()

False

UPTOHERE:
* get tensors on GPU
* show how to go back and forth between GPU and non-GPU
* go back through headings and make sure code is good to go...


In [ ]:
device = "gpu" if torch.cuda.is_available() else "cpu"