## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.version.cuda)

2.8.0+cu126
False
12.6


In [2]:
print("Hello Im excited to learn PyTorch!")

Hello Im excited to learn PyTorch!


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

Tensors are ways of representing data in a  multidimensional way


### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://docs.pytorch.org/docs/stable/tensors.html

### Types of Tensors (Examples)
Scalar = 1
Vector = [1, 2]
Matrix = [1,2,3,4]
Tensor = [[1,2], [3,4], [5,6], [7, 8]]


In [4]:
# scalar
scaler = torch.tensor(7)
scaler


tensor(7)

In [5]:
scaler.ndim

0

In [6]:
# Get tensor back as Python int
scaler.item()

7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

# think of dimensions as number of pair square bracket

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html


In [18]:
### Create a random tensor of shape or size(3,4)

random_tensor = torch.rand(10, 10)
random_tensor

tensor([[0.5502, 0.6438, 0.6845, 0.6788, 0.4296, 0.4093, 0.0115, 0.0082, 0.6809,
         0.5447],
        [0.8549, 0.2180, 0.8973, 0.6212, 0.4169, 0.7569, 0.7865, 0.7625, 0.4675,
         0.3350],
        [0.5909, 0.0730, 0.1400, 0.4951, 0.2481, 0.3981, 0.4419, 0.8943, 0.6071,
         0.1232],
        [0.3610, 0.8722, 0.9034, 0.4018, 0.4277, 0.8507, 0.6441, 0.1883, 0.3531,
         0.4480],
        [0.0540, 0.9415, 0.7742, 0.7574, 0.2586, 0.6382, 0.9104, 0.2204, 0.9064,
         0.6721],
        [0.0410, 0.3050, 0.8137, 0.1794, 0.2454, 0.1733, 0.5798, 0.1370, 0.9867,
         0.1309],
        [0.7281, 0.0166, 0.6371, 0.8375, 0.4159, 0.5296, 0.5524, 0.0795, 0.8035,
         0.3393],
        [0.6911, 0.2529, 0.3424, 0.4832, 0.5111, 0.7284, 0.6032, 0.8257, 0.9302,
         0.4271],
        [0.9950, 0.9243, 0.9990, 0.0997, 0.7306, 0.3791, 0.6684, 0.9072, 0.4119,
         0.3779],
        [0.7678, 0.1246, 0.2583, 0.9514, 0.1505, 0.2552, 0.2235, 0.5735, 0.2198,
         0.4543]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor = torch.rand(1, 2, 4)
random_tensor

tensor([[[0.6381, 0.0825, 0.1206, 0.4424],
         [0.5558, 0.4163, 0.0359, 0.0083]]])

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
torch.rand(3, 3)

tensor([[0.8781, 0.6011, 0.0827],
        [0.2265, 0.6722, 0.1324],
        [0.5143, 0.7692, 0.1759]])

In [23]:
torch.rand(size=(3, 3))

tensor([[0.6477, 0.9296, 0.1841],
        [0.0914, 0.3879, 0.8018],
        [0.5690, 0.2968, 0.8759]])

### Zeros and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [27]:
# Use torch.range() <--- being deprecated
torch.range(0, 10)

/tmp/ipython-input-1276390300.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Notes:** Tensor datatypes is one the big 3 errors you will run into with PyTorch and Deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


https://docs.pytorch.org/docs/stable/tensor_attributes.html#dtype-doc

In [30]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
# float16 tensor
float_36_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

In [33]:
float_36_tensor.dtype

torch.float16

In [34]:
# float32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (eg float32, float16, float64 - the float is teh precision in computing ie how computers store numbers /) https://docs.pytorch.org/docs/stable/tensor_attributes.html#dtype-doc
                               device=None, # cpu, cuda, gpu. What device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensors operations


In [35]:
### chaing tensor dtype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (Tensor attributes)

1. Tensors not right datatupe - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - to get device from a tensor, can use `tensor.device`

In [38]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7660, 0.0357, 0.6144, 0.7321],
        [0.9552, 0.2418, 0.4361, 0.0840],
        [0.2262, 0.9854, 0.4699, 0.1032]])

In [39]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7660, 0.0357, 0.6144, 0.7321],
        [0.9552, 0.2418, 0.4361, 0.0840],
        [0.2262, 0.9854, 0.4699, 0.1032]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [40]:
# shape and size
print(some_tensor.shape) # this is an attribute
print(some_tensor.size()) # this is a method

torch.Size([3, 4])
torch.Size([3, 4])


### Manipulating Tensors (tensor operations)

Tensor operations include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [41]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [42]:
# Multiplication
tensor = torch.tensor([1, 2, 3])
tensor * 10

tensor([10, 20, 30])

In [43]:
# Subraction
tensor = torch.tensor([1, 2, 3])
tensor - 10

tensor([-9, -8, -7])

In [44]:
# Try out PyTorch in-built functions
# multiplication
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
# Addition
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main wats of performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix Multiplication (dot product)

More information about multiplying matrices:

https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` wont work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> resulting shape `(2, 2)`
* `(3,2) @ (2,3)` -> resulting shape `(3, 3)`


In [46]:
torch.matmul(torch.rand(3,10), torch.rand(10,2)).shape

torch.Size([3, 2])

In [47]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
# using the @ symbol which also mean matrix multiplication
tensor @ tensor

tensor(14)

In [50]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.31 ms, sys: 0 ns, total: 2.31 ms
Wall time: 3.14 ms


In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 511 µs, sys: 0 ns, total: 511 µs
Wall time: 405 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [53]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matrix multiplication)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [54]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a **transpose**. A **transpose** switches the axes or dimensions of a given tensor.

In [55]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [56]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [57]:
# The matrix multiplcation operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggregation)

In [58]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [59]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [60]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [61]:
# Find the mean - note the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x, dtype=torch.float32), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [62]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [63]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [64]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [65]:
# Find the position in tensor that has the minimum balue witj agrmin() -> return index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [66]:
# Find the position in tensor that has the maximum balue witj agrmin() -> return index position of target tensor where the minimum value occurs
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors.

* Reshaping - reshapes an input tensor to a defined shape.
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [68]:
# Lets create a tensor
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [69]:
# Add an extra dimension
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [70]:
# Add an extra dimension
x_reshaped = x.reshape(2, 5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [71]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [72]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [73]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [74]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [86]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor: {x_squeezed.shape}")

Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
Previous tensor: torch.Size([2, 5])

New tensor: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
New tensor: torch.Size([2, 5])


In [87]:
# torch.unsqueeze() - adds a signle dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous tensor: {x_squeezed.shape}")

# Remove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor: {x_unsqueezed.shape}")


Previous tensor: tensor([[ 5.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])
Previous tensor: torch.Size([2, 5])

New tensor: tensor([[[ 5.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]])
New tensor: torch.Size([1, 2, 5])


In [88]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels (rgb)]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [color_channels (rgb), height, width]


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy.

In [89]:
# create tensor

import torch

x = torch.arange(1, 10).reshape(1, 3, 3) # the reshape (a*b*c) should match with the number of digit in original
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [93]:
# Lets index on the middle bracket (dim1)
x[0][0]

tensor([1, 2, 3])

In [94]:
# Lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [95]:
# Lets index to get the number 9
x[0][2][2]

tensor(9)

In [96]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [97]:
# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [99]:
# Get all values of 0th dimsion but only the 1 index values of the 1st and 2nd diemsnion
x[:, 1, 1]

tensor([5])

In [100]:
# Get first value of 0th dimsion but only the 1 index values of the 1st and 2nd diemsnion
x[0, 1, 1] # this is teh same as x[0][1][1]

tensor(5)

In [102]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # this is the same as x[0][0]

tensor([1, 2, 3])

In [103]:
x[0][0]

tensor([1, 2, 3])

In [105]:
# Index on x to return 9
x[0,2,2] #x[0][2][2]

tensor(9)

In [122]:
# Index on x to return 3, 6, 9
x[:, :, 2:]

tensor([[[3],
         [6],
         [9]]])

In [123]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library. And because of this, PyTorch has functionality to interract with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)
`
* PyTorch tensor to NumPy -> `torch.Tensor.numpy()`

In [2]:
# Numpy Array to Tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
# tensor = torch.from_numpy(array).type(torch.float32) # if you want to convert that to float32
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [3]:
array.dtype

dtype('float64')

In [4]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [5]:
# change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor # note when we used from_numpy to create a new tensor so the original array when changed doesnt change the new tensor ie does create a new tensor in memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [6]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [7]:
numpy_tensor.dtype

dtype('float32')

In [8]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor # the numpy_tensor doesnt change even if you change the tensor ie they do not share teh same memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (Trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**. Essentially what the random seed does is "flavour" the randomness.


In [11]:
torch.rand(3,3)

tensor([[0.6536, 0.6849, 0.6722],
        [0.2752, 0.1766, 0.9846],
        [0.2744, 0.4985, 0.7055]])

In [12]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6817, 0.5965, 0.1671, 0.0949],
        [0.3485, 0.2956, 0.0102, 0.8800],
        [0.0791, 0.5801, 0.5850, 0.5171]])
tensor([[0.1021, 0.2392, 0.6327, 0.1058],
        [0.3929, 0.7858, 0.6138, 0.6305],
        [0.5671, 0.0133, 0.5586, 0.6037]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [13]:
# Lets make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42 # this is teh randomness flavour

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility
* https://docs.pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

### Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory(good).

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options ...see this post of the options to get: https://timdettmers.com/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

To get the GPU on google colab: In any notebook --> Runtime --> Change Runtime Type --> select Hardware accelerator (CPU, GPU, TPU...) --> save



In [1]:
!nvidia-smi

Mon Nov 17 10:00:24 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch~

In [3]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:

https://docs.pytorch.org/docs/stable/notes/cuda.html

E.g run on GPU if available else default to CPU

In [4]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices (ie number of GPUs)
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using GPU results in faster computations.


In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4- Moving Tensors back to the CPU

some computations requires you to run in CPU like numpy

In [8]:
# if tensor is on GPU, can't transof rit in Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
# To fix the GPU tensor with NumPy issue,we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Exercises

In [2]:
import torch

In [3]:
# Exercise 2
# Create a random tensor with shape (7, 7).
x = torch.rand(7, 7)

In [4]:
x

tensor([[0.9365, 0.9001, 0.8553, 0.2066, 0.9945, 0.6332, 0.7421],
        [0.1291, 0.3799, 0.5359, 0.7086, 0.3226, 0.9001, 0.8490],
        [0.9740, 0.1635, 0.1806, 0.6624, 0.2910, 0.1648, 0.9720],
        [0.0989, 0.2660, 0.8803, 0.3216, 0.2904, 0.1805, 0.9035],
        [0.0816, 0.1523, 0.5167, 0.0058, 0.6725, 0.5838, 0.0605],
        [0.5204, 0.8492, 0.0768, 0.2499, 0.6439, 0.0740, 0.2834],
        [0.1947, 0.3302, 0.0879, 0.8350, 0.2510, 0.5011, 0.0368]])

In [5]:
# Exercise 3
# Perform a matrix multiplication on the tensor from 2 with
#another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor).

x_2 = torch.rand(1, 7)
x_2

tensor([[0.4529, 0.6369, 0.7986, 0.3315, 0.2076, 0.3195, 0.4501]])

In [6]:
mat_mul = torch.mm(x, x_2.T)
mat_mul

tensor([[2.4918],
        [1.7000],
        [1.4596],
        [1.5485],
        [0.9020],
        [1.2056],
        [0.8743]])

In [9]:
# Exercise 4
# Set the random seed to 0 and do exercises 2 & 3 over again.

torch.manual_seed(0)
x = torch.rand(7, 7)

torch.manual_seed(0)
x_2 = torch.rand(1, 7)

mat_mul = torch.matmul(x, x_2.T)
mat_mul


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [1]:
# Exercise 5
# Speaking of random seeds, we saw how to set it
# with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234.

# Answer:
# Pytorch has a GPU version - they use CUDA to represent that
import torch

torch.cuda.manual_seed(1234)

# to see all available GPUs
torch.cuda.manual_seed_all(1234)

In [3]:
# Exercise 6
# Create two random tensors of shape (2, 3) and
# send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors
# (this doesn't have to be the GPU random seed).

#imports
import torch

# set device to gpu
device = "cuda" if torch.cuda.is_available() else "cpu"

# create tensor and set to device gpu
torch.manual_seed(1234)
tensor_A = torch.rand(2, 3).to(device)

torch.manual_seed(42)
tensor_B = torch.rand(2, 3).to(device)

tensor_A, tensor_B


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]], device='cuda:0'))

In [4]:
# Exercise 7
# Perform a matrix multiplication on the tensors
# you created in 6 (again, you may have to adjust the shapes of one of the tensors)

# Answer:
mat_mul = torch.mm(tensor_A, tensor_B.T)
mat_mul

tensor([[0.4928, 0.3409],
        [0.6451, 0.7955]], device='cuda:0')

In [6]:
# Exercise 8
# Find the maximum and minimum values of the output of 7.

print('maximum:', mat_mul.max(), '\n', 'minimum:', mat_mul.min())

maximum: tensor(0.7955, device='cuda:0') 
 minimum: tensor(0.3409, device='cuda:0')


In [7]:
# Exercise 9:
# Find the maximum and minimum index values of the output of 7.

print('maximum lcation (index):', mat_mul.argmax(), '\n', 'minimum location(index):', mat_mul.argmin())


maximum lcation (index): tensor(3, device='cuda:0') 
 minimum location(index): tensor(1, device='cuda:0')


In [6]:
# Exercise 10
# Make a random tensor with shape (1, 1, 1, 10) and
# then create a new tensor with all the 1 dimensions removed to be left
# with a tensor of shape (10). Set the seed to 7 when you create
# it and print out the first tensor and it's shape as well as the second tensor and it's shape.

#Answer:
import torch

tensor_A = torch.rand(1, 1, 1, 10)
print(tensor_A, tensor_A.shape)

# squeeze to remove all dimensions of size 1
tensor_B = tensor_A.squeeze()
print(tensor_B, tensor_B.shape)

torch.manual_seed(7)
tensor_C = torch.rand(1, 1, 1, 10)
print(tensor_C, tensor_C.shape)


# squeeze to remove all dimensions of size 1
torch.manual_seed(7)
tensor_D = tensor_C.squeeze()
print(tensor_D, tensor_D.shape)





tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
