In [1]:
import torch 
torch.__version__

/home/jason/anaconda3/envs/tadac/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'1.12.0'

## Scalar

In [2]:
# a zero dimension tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# dimension of a tensor
scalar.ndim

0

In [4]:
# from torch.Tensor to a Python integer
scalar.item()

7

## Vector

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# check the number of dimensions of vector
vector.ndim

1

In [7]:
# check shape of vector
vector.shape 

torch.Size([2])

## MATRIX, TENSOR

In [8]:
# matrix 
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# check number of dimensions
MATRIX.ndim

2

In [54]:
# check shape of matrix
MATRIX.shape 

torch.Size([2, 2])

In [10]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [11]:
# ndim
TENSOR.ndim

3

In [12]:
# shape
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors

In [17]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype, random_tensor.ndim, random_tensor.shape

(tensor([[0.9676, 0.5845, 0.6321, 0.7644],
         [0.5733, 0.5897, 0.9345, 0.5099],
         [0.1225, 0.0461, 0.6076, 0.5976]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [59]:
# a random tensor of size (224, 224,3)
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [60]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [61]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [62]:
# use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10)

/tmp/ipykernel_5529/1306563728.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


In [63]:
# create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
# zeros like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
# ones like
one_zeros = torch.ones_like(input=zero_to_ten)
one_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

### defaul type
`torch.float32` or `torch.float`

In [66]:
# default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None,  # defaults to None, which uses the default tensor type
                               requires_grad=False)  # if True, operations performed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [67]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [68]:
# create a tensor
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors

### Basic operations

In [69]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [70]:
tensor*10

tensor([10, 20, 30])

In [71]:
tensor

tensor([1, 2, 3])

In [72]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [73]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [74]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [75]:
print(tensor, "*", tensor)
print("Equals: ", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


### Matrix multiplication

In [76]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [77]:
# element-wise matrix multiplication 
tensor * tensor

tensor([1, 4, 9])

In [78]:
# matix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [79]:
# "@" symbol for matrix multiplication
tensor @ tensor

tensor(14)

In [80]:
%%time
value  =0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: user 205 µs, sys: 64 µs, total: 269 µs
Wall time: 318 µs


tensor(14)

In [81]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 160 µs, sys: 50 µs, total: 210 µs
Wall time: 208 µs


tensor(14)

## One of the most common errors in deep learning (shape errors)

In [82]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)


In [83]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2, out_features=6)
x = tensor_A
output = linear(x)


print(f"Input shape: {x.shape}\n")
print(f"Weight shape: {linear.weight.shape}")
print(f"Weight: {linear.weight}")
print(f"Bias: {linear.bias}")
print(f"Output:\n {output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Weight shape: torch.Size([6, 2])
Weight: Parameter containing:
tensor([[ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]], requires_grad=True)
Bias: Parameter containing:
tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045],
       requires_grad=True)
Output:
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


`torch.nn.Linear()`

$$
y = x\cdot{A^T} + b
$$

In [84]:
bias = torch.tensor([ 0.5224,  0.0958,  0.3410, -0.0998,  0.5451,  0.1045])
weights = torch.tensor([
        [ 0.5406,  0.5869],
        [-0.1657,  0.6496],
        [-0.1549,  0.1427],
        [-0.3443,  0.4153],
        [ 0.6233, -0.5188],
        [ 0.6146,  0.1323]])

print("bias.shape: ", bias.shape)
print("weights.shape: ", weights.shape)
print("x.shape: ", x.shape)

y = torch.matmul(x,weights.T) + bias
y 

bias.shape:  torch.Size([6])
weights.shape:  torch.Size([6, 2])
x.shape:  torch.Size([3, 2])


tensor([[2.2368, 1.2293, 0.4715, 0.3865, 0.1308, 0.9837],
        [4.4918, 2.1971, 0.4471, 0.5285, 0.3398, 2.4775],
        [6.7468, 3.1649, 0.4227, 0.6705, 0.5488, 3.9713]])

## Finding the min, max, mean, sum, etc

In [85]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
print(f"Minimun: {x.min()}")
print(f"Maximum: {x.max()}")

Minimun: 0
Maximum: 90


In [87]:
print(f"Mean 1: {x.mean()}") # this will error

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
print(f"Mean 1: {x.type(torch.float32).mean()}") # won't work without float datatype

Mean 1: 45.0


In [ ]:
y = torch.arange(0,100, 10, dtype=torch.float32)
print(f"Mean 1: {y.mean()}")

Mean 1: 45.0


In [ ]:
print(f"Sum: {x.sum()}")

Sum: 450


In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

## Positional min/max

In [ ]:
# create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# return index of max and min values
print(f"idx of max value: {tensor.argmax()}")
print(f"idx of min value: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
idx of max value: 8
idx of min value: 0


## Change tensor datatype

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor_int16 = tensor.type(torch.int16)
tensor_int16.dtype

torch.int16

## Reshaping, stacking, squeezing, and unsqueezing

In [ ]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
z[:,0] = 5
z,  x 

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"\nPrevious shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])

Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])

New shape: torch.Size([7])


In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"\nPrevious shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])

Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])

New shape: torch.Size([1, 7])


In [ ]:
# to rearrange the order of axes values 
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2,0,1)

## Indexing (selecting data from tensors)

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"First square bracket:\n {x[0]}")
print(f"Second square bracket:\n {x[0][0]}")
print(f"Third square bracket:\n {x[0][0][0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket:
 tensor([1, 2, 3])
Third square bracket:
 1


In [ ]:
# get all values of 0th dimension  and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th dimension  and the 0 index of 2nd dimension
x[:,1]

tensor([[4, 5, 6]])

In [ ]:
x


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:].shape, x.shape

(torch.Size([1, 3, 3]), torch.Size([1, 3, 3]))

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors & Numpy


In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = tensor.type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [ ]:
array  = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [ ]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A: \n {random_tensor_A}")
print(f"Tensor B: \n {random_tensor_B}")

random_tensor_A == random_tensor_B

Tensor A: 
 tensor([[0.1623, 0.3355, 0.9816, 0.0925],
        [0.8324, 0.7634, 0.2090, 0.2338],
        [0.6740, 0.3459, 0.0536, 0.2987]])
Tensor B: 
 tensor([[0.8287, 0.0395, 0.4987, 0.5892],
        [0.6680, 0.2204, 0.9596, 0.0467],
        [0.5744, 0.6095, 0.3127, 0.4480]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# torch.manual_seed(seed)
import torch

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C: \n{random_tensor_C}\n")
print(f"Tensor D: \n{random_tensor_D}\n")

random_tensor_C == random_tensor_D

Tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])



tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
# torch.manual_seed(seed)
import torch

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

# torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C: \n{random_tensor_C}\n")
print(f"Tensor D: \n{random_tensor_D}\n")

random_tensor_C == random_tensor_D

Tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D: 
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])



tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# torch.manual_seed(seed)
import torch

RANDOM_SEED = 1234
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(f"Tensor C: \n{random_tensor_C}\n")
print(f"Tensor D: \n{random_tensor_D}\n")

random_tensor_C == random_tensor_D

Tensor C: 
tensor([[0.0290, 0.4019, 0.2598, 0.3666],
        [0.0583, 0.7006, 0.0518, 0.4681],
        [0.6738, 0.3315, 0.7837, 0.5631]])

Tensor D: 
tensor([[0.7749, 0.8208, 0.2793, 0.6817],
        [0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294]])



tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

## Runnng tesors on GPU 

In [ ]:
!nvidia-smi

Thu May 25 13:52:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 40%   40C    P8    31W / 250W |   3889MiB / 11011MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# check for GPU
import torch
torch.cuda.is_available()

True

In [89]:
# set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of devices
torch.cuda.device_count()

1

In [90]:
# create tensor (default cpu)
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [91]:
# if tensor is on GPU, cant transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [92]:
# copy tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [93]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')