# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tensor2 = torch.rand(7,7)

# Perform matrix multiplication 
tensor_mult = torch.matmul(tensor, tensor2)
tensor @ tensor2

tensor([[2.3265, 1.4151, 1.4595, 1.1784, 1.1547, 1.6001, 2.2779],
        [2.0068, 1.2557, 1.2311, 1.2165, 0.7891, 1.6724, 1.3459],
        [1.5602, 1.3609, 0.9012, 0.9696, 0.7927, 1.2862, 1.6487],
        [2.3357, 1.1354, 1.5744, 1.2045, 1.4957, 1.7178, 2.3303],
        [2.9000, 1.9628, 1.8961, 1.9873, 1.8628, 2.4410, 2.9073],
        [2.4596, 1.3890, 1.6925, 1.5321, 1.3406, 1.7228, 2.1988],
        [1.4818, 1.3307, 0.8560, 1.3905, 0.9151, 1.0858, 2.1017]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
t1 = torch.rand(2,2)
t2 = torch.rand(1,2)

# Matrix multiply tensors
tm = t1 @ t2.T
tm, tm.shape

(tensor([[0.6397],
         [0.1109]]),
 torch.Size([2, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [27]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(RANDOM_SEED)

cuda



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [31]:
# Set random seed

torch.cuda.manual_seed(1234)

# Check for access to GPU

print(f"device: {torch.cuda.is_available(), device}")

# Create two random tensors on GPU

t11 = torch.rand(2,3)
t12 = torch.rand(2,3)
t11_gpu = t11.to(device)
t12_gpu = t12.to(device)

print(t11_gpu, t11_gpu.device)
print(t12_gpu, t12_gpu.device)

device: (True, 'cuda')
tensor([[0.2820, 0.3742, 0.0237],
        [0.4910, 0.1235, 0.1143]], device='cuda:0') cuda:0
tensor([[0.4725, 0.5751, 0.2952],
        [0.7967, 0.1957, 0.9537]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [43]:
# Perform matmul on tensor_A and tensor_B

t11m = torch.mm(t11_gpu.T, t12_gpu)
t11m

tensor([[0.5244, 0.2583, 0.5515],
        [0.2751, 0.2393, 0.2282],
        [0.1023, 0.0360, 0.1160]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [44]:
# Find max
t11m_max = torch.max(t11m)
print(f"Maximum: {t11m_max}")

# Find min
t11m_min = torch.min(t11m)
print(f"Minimum: {t11m_min}")

Maximum: 0.5515242218971252
Minimum: 0.03600599616765976


### 9. Find the maximum and minimum index values of the output of 7.

In [46]:
# Find arg max
print(t11m)

print(f"Arg max: {torch.argmax(t11m)}")

# Find arg min
print(f"Arg min: {torch.argmin(t11m)}")

tensor([[0.5244, 0.2583, 0.5515],
        [0.2751, 0.2393, 0.2282],
        [0.1023, 0.0360, 0.1160]], device='cuda:0')
Arg max: 2
Arg min: 7



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [49]:
# Set seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

# Create random tensor
t3 = torch.rand(1,1,1,10)

# Remove single dimensions
t3_sq = torch.squeeze(t3)

# Print out tensors and their shapes
print(t3, t3.shape)
print(t3_sq, t3_sq.shape)


tensor([[[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936,
           0.9408, 0.1332]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332]) torch.Size([10])
