# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor

tensor([[0.9473, 0.4796, 0.8238, 0.2162, 0.4292, 0.2930, 0.4013],
        [0.0909, 0.9036, 0.1976, 0.7709, 0.3027, 0.3923, 0.5768],
        [0.2172, 0.4720, 0.0324, 0.1137, 0.2709, 0.5308, 0.0708],
        [0.4380, 0.2407, 0.6845, 0.4044, 0.4465, 0.0734, 0.6406],
        [0.6649, 0.3130, 0.4927, 0.1371, 0.5819, 0.9410, 0.6062],
        [0.3131, 0.9110, 0.0606, 0.9862, 0.9770, 0.1302, 0.8300],
        [0.3633, 0.5432, 0.0048, 0.7753, 0.5374, 0.2534, 0.7470]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [10]:
# Create another random tensor
tensor2= torch.rand(1,7)
# Perform matrix multiplication
torch.mm(tensor2, tensor)

tensor([[1.5162, 1.4619, 1.2879, 0.9661, 1.1961, 1.2263, 1.2790]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [49]:
# Set manual seed
random_seed=0
# Create two random tensors
torch.manual_seed(random_seed)
tensor_a=torch.rand(7,7)
torch.manual_seed(random_seed)
tensor_b=torch.rand(1,7)

# Matrix multiply tensors
mul= torch.mm(tensor_a,tensor_b.T)
mul, mul.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [58]:
# Set random seed
torch.cuda.manual_seed(1234)
torch.cuda.set_device(0)
# Check for access to GPU
device= "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")
# Create two random tensors on GPU
torch.cuda.manual_seed(1234)
tensor_c = torch.rand(2,3).to(device)
torch.cuda.manual_seed(1234)
tensor_d = torch.rand(2,3).to(device)
tensor_c, tensor_d


Device: cuda


(tensor([[0.7529, 0.8579, 0.6870],
         [0.0051, 0.1757, 0.7497]], device='cuda:0'),
 tensor([[0.6047, 0.1100, 0.2121],
         [0.9704, 0.8369, 0.2820]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [47]:
# Perform matmul on tensor_A and tensor_B
mul2=torch.mm(tensor_c,tensor_d.T)
mul2,mul2.shape

(tensor([[1.1941, 0.6911],
         [0.3175, 0.2087]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [60]:
# Find max
max= torch.max(mul2)
# Find min
min= torch.min(mul2)
max,min

(tensor(1.1941, device='cuda:0'), tensor(0.2087, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [66]:
# Find arg max
max2= torch.argmax(mul2)

# Find arg min
min2=torch.argmin(mul2)
max2,min2

(tensor(0, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor(0.2087, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [69]:
# Set seed
torch.cuda.manual_seed(7)

# Create random tensor
tensor_f = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_g=tensor_f.squeeze()

# Print out tensors and their shapes
print(f"tensor_f: {tensor_f}")
print(f"tensfor_f_shape: {tensor_f.shape}")
print(f"tensor_g:{tensor_g}")
print(f"tensor_g_shape: {tensor_g.shape}")

tensor_f: tensor([[[[0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186, 0.6962,
           0.5300, 0.2560]]]])
tensfor_f_shape: torch.Size([1, 1, 1, 10])
tensor_g:tensor([0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186, 0.6962, 0.5300,
        0.2560])
tensor_g_shape: torch.Size([10])
