# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
tensor_1 = torch.rand(size=(7, 7))
tensor_1

tensor([[0.0755, 0.1564, 0.9935, 0.4271, 0.9132, 0.9082, 0.1017],
        [0.8199, 0.0456, 0.6622, 0.7933, 0.9819, 0.7561, 0.8148],
        [0.6012, 0.0383, 0.1678, 0.1504, 0.0703, 0.2359, 0.3658],
        [0.2206, 0.0539, 0.6748, 0.8869, 0.2640, 0.4490, 0.7305],
        [0.1817, 0.1281, 0.2186, 0.1159, 0.4754, 0.0669, 0.7637],
        [0.9168, 0.8192, 0.5398, 0.4910, 0.9546, 0.4542, 0.0928],
        [0.6931, 0.8561, 0.4523, 0.8727, 0.8310, 0.0653, 0.5174]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
tensor_2 = torch.rand(size=(1, 7))

# Perform matrix multiplication 
torch.matmul(tensor_1, tensor_2.T)

tensor([[2.1719],
        [3.4911],
        [1.3596],
        [2.5323],
        [1.3790],
        [2.6031],
        [2.7743]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_3 = torch.rand(size=(7, 7))
tensor_4 = torch.rand(size=(1, 7))

# Matrix multiply tensors
torch.matmul(tensor_3, tensor_4.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.cuda.manual_seed_all(1234)

# Check for access to GPU
gpu_available = torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"GPU availability: {gpu_available}")
print(f"device: {device}")

# Create two random tensors on GPU
torch.manual_seed(1234)
tensor_5 = torch.rand(size=(2, 3)).to(device=device)
tensor_6 = torch.rand(size=(2, 3)).to(device=device)

tensor_5, tensor_6

GPU availability: True
device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
tensor_8 = torch.matmul(tensor_5, tensor_6.T)
tensor_8

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
print(f"max: {tensor_8.max()}")
# Find min
print(f"max: {tensor_8.min()}")


max: 0.5617256760597229
max: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
print(f"max index: {tensor_8.argmax()}")

# Find arg min
print(f"min index: {tensor_8.argmin()}")


max index: 3
min index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [11]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_9 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_10 = tensor_9.squeeze()

# Print out tensors and their shapes
print(tensor_9, tensor_9.shape)
print(tensor_10, tensor_10.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
